# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest    
          
    steps:
    - name: Install mssql
      uses: potatoqualitee/mssqlsuite@v1.7
      with:
        install: sqlengine, sqlclient, sqlpackage, localdb

    - name: Create database for testing
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "create database SFC_Test"
      
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Update appsettings.json for tests
      run: |
        sed -i 's/(localdb)\\\\MSSQLLocalDB/localhost/g' src/SFC.Tests/appsettings.json        
        sed -i 's/Trusted_Connection=True/User Id=sa;Password=dbatools.I0/g' src/SFC.Tests/appsettings.json                      
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
