@startuml
center header <font size=25>/api/v1.0/accounts</font>
User -> SFC.UserApi : <<POST>> /api/v1.0/accounts
SFC.UserApi -> SFC.Processes : <<Command>> RegisterUserCommand
SFC.Processes -> SFC.Accounts : <<Query>> GetAccountByLoginNameRequest
SFC.Accounts -> SFC.Processes : <<Return>> null
SFC.Processes -> SFC.Notifications : <<Command>> SetNotificationEmailCommand
SFC.Notifications -> SFC.Processes : <<Return>> 
SFC.Processes -> SFC.Notifications : <<Command>> SendNotificationCommand
SFC.Notifications -> SFC.Processes : <<Return>> 
SFC.Processes -> SFC.UserApi : <<Return>> 
SFC.UserApi -> User: <<Return>> 200
@enduml
