@startuml
center header <font size=25>/api/v1.0/admin/alertNotificationsWithUserData</font>
User -> SFC.AdminApi : <<GET>> /api/v1.0/admin/alertNotificationsWithUserData
SFC.AdminApi -> SFC.Accounts : <<Query>> SearchAccountRequest
SFC.Accounts -> SFC.AdminApi : <<Return>> SearchAccountResponse
SFC.AdminApi -> SFC.Notifications : <<Query>> GetSendNotificationsCountRequest
SFC.Notifications -> SFC.AdminApi : <<Return>> GetSendNotificationsCountResponse
SFC.AdminApi -> User: <<Return>> 200
@enduml
