@startuml
center header <font size=25>/api/v1.0/user/sensors</font>
User -> SFC.UserApi : <<POST>> /api/v1.0/user/sensors
SFC.UserApi -> SFC.Sensors : <<Command>> RegisterSensorCommand
SFC.Sensors -> SFC.UserApi : <<Return>> 
SFC.UserApi -> User: <<Return>> 200
@enduml
