@startuml
center header <font size=25>/api/v1.0/accounts/{id}/confirmation</font>
User -> SFC.UserApi : <<POST>> /api/v1.0/accounts/{id}/confirmation
SFC.UserApi -> SFC.Processes : <<Command>> ConfirmUserCommand
SFC.Processes -> SFC.Accounts : <<Command>> CreateAccountCommand
SFC.Accounts -> SFC.AdminApi : <<Event>> AccountCreatedEvent
SFC.AdminApi -> SFC.Accounts : <<Return>> 
SFC.Accounts -> SFC.Processes : <<Return>> 
SFC.Processes -> SFC.Alerts : <<Command>> CreateAlertCommand
SFC.Alerts -> SFC.AdminApi : <<Event>> AlertCreatedEvent
SFC.AdminApi -> SFC.Alerts : <<Return>> 
SFC.Alerts -> SFC.Processes : <<Event>> AlertCreatedEvent
SFC.Processes -> SFC.Notifications : <<Command>> SendNotificationCommand
SFC.Notifications -> SFC.Processes : <<Return>> 
SFC.Processes -> SFC.Alerts : <<Return>> 
SFC.Alerts -> SFC.Processes : <<Return>> 
SFC.Processes -> SFC.UserApi : <<Return>> 
SFC.UserApi -> User: <<Return>> 200
@enduml
