@startuml
center header <font size=25>/api/v1.0/admin/sendNotificationsByUser</font>
User -> SFC.AdminApi : <<GET>> /api/v1.0/admin/sendNotificationsByUser
SFC.AdminApi -> SFC.Notifications : <<Query>> GetAllSendNotificationsByUserRequest
SFC.Notifications -> SFC.AdminApi : <<Return>> GetAllSendNotificationsByUserResponse
SFC.AdminApi -> User: <<Return>> 200
@enduml
